version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/01-edu-repos/Branch-Blockchain/tests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      hardhat-ecosystem:
        patterns:
          - "@nomicfoundation/*"
          - "hardhat"
          - "web3"
