<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
	<title>random.php</title>
</head>
<body>
<code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br /><br /></span><span style="color: #FF8000">//&nbsp;https://secure.php.net/manual/en/function.srand.php#90215<br /></span><span style="color: #0000BB">srand&nbsp;</span><span style="color: #007700">(</span><span style="color: #0000BB">microtime&nbsp;</span><span style="color: #007700">(</span><span style="color: #0000BB">true</span><span style="color: #007700">));<br /><br />function&nbsp;</span><span style="color: #0000BB">generate_random_text&nbsp;</span><span style="color: #007700">(</span><span style="color: #0000BB">$length</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #0000BB">$chars&nbsp;&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #DD0000">"abcdefghijklmnopqrstuvwxyz"</span><span style="color: #007700">;<br />&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #0000BB">$chars&nbsp;</span><span style="color: #007700">.=&nbsp;</span><span style="color: #DD0000">"ABCDEFGHIJKLMNOPQRSTUVWXYZ"</span><span style="color: #007700">;<br />&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #0000BB">$chars&nbsp;</span><span style="color: #007700">.=&nbsp;</span><span style="color: #DD0000">"1234567890"</span><span style="color: #007700">;<br /><br />&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #0000BB">$text&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #DD0000">''</span><span style="color: #007700">;<br />&nbsp;&nbsp;&nbsp;&nbsp;for(</span><span style="color: #0000BB">$i&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">0</span><span style="color: #007700">;&nbsp;</span><span style="color: #0000BB">$i&nbsp;</span><span style="color: #007700">&lt;&nbsp;</span><span style="color: #0000BB">$length</span><span style="color: #007700">;&nbsp;</span><span style="color: #0000BB">$i</span><span style="color: #007700">++)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #0000BB">$text&nbsp;</span><span style="color: #007700">.=&nbsp;</span><span style="color: #0000BB">$chars</span><span style="color: #007700">[</span><span style="color: #0000BB">rand&nbsp;</span><span style="color: #007700">()&nbsp;%&nbsp;</span><span style="color: #0000BB">strlen&nbsp;</span><span style="color: #007700">(</span><span style="color: #0000BB">$chars</span><span style="color: #007700">)];<br />&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;</span><span style="color: #0000BB">$text</span><span style="color: #007700">;<br />}<br /><br /><br /></span>
</span>
</code></body>
</html>
